name: movieapps
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.3
  shared_preferences: ^2.0.8
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  flutter_product_card: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
